books/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    HomeView, AboutUsView, post_search, BookListView, BookDetailView,
    BookListByTagView, AddBookmarkView, RemoveBookmarkView, AuthorListView,
    AuthorDetailView, view_pdf_in_new_tab, view_pdf, AddCommentView,
    UpdateCommentView, DeleteCommentView, load_more_comments, BookmarksView,
    BookViewSet, AuthorViewSet
)

router = DefaultRouter()
router.register(r'api/books', BookViewSet, basename='book')
router.register(r'api/authors', AuthorViewSet, basename='author')

app_name = 'books'

urlpatterns = [
    # Django views
    path('', BookListView.as_view(), name='book_list'),
    path('search/', post_search, name='search'),
    path('books/<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('tag/<slug:tag_slug>/', BookListByTagView.as_view(), name='book_list_by_tag'),
    path('books/<int:pk>/add_bookmark/', AddBookmarkView.as_view(), name='add_bookmark'),
    path('books/<int:pk>/remove_bookmark/', RemoveBookmarkView.as_view(), name='remove_bookmark'),
    path('authors/', AuthorListView.as_view(), name='author_list'),
    path('authors/<int:pk>/', AuthorDetailView.as_view(), name='author_detail'),
    path('view_pdf_in_new_tab/<int:book_id>/', view_pdf_in_new_tab, name='view_pdf_in_new_tab'),
    # path('view_pdf_file/<int:book_id>/', view_pdf, name='view_pdf_file'),
    path('books/<int:book_id>/comment/add/', AddCommentView.as_view(), name='add_comment'),
    path('comment/edit/<int:comment_id>/', UpdateCommentView.as_view(), name='edit_comment'),
    path('comment/delete/<int:comment_id>/', DeleteCommentView.as_view(), name='delete_comment'),
    path('books/<int:book_id>/comment/update/<int:comment_id>/', UpdateCommentView.as_view(), name='update_comment'),
    path('books/load-more-comments/<int:book_id>/', load_more_comments, name='load_more_comments'),
    path('bookmarks/', BookmarksView.as_view(), name='bookmarks'),
    path('', HomeView.as_view(), name='home'),
    path('about-us/', AboutUsView.as_view(), name='about_us'),

    # DRF views
    path('', include(router.urls)),
]

librarysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)
from books.views import AboutUsView, HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('books/', include('books.urls', namespace='books')),
    path('subscriptions/', include('subscriptions.urls', namespace='subs')),
    path('', HomeView.as_view(), name='home'),
    path('about-us/', AboutUsView.as_view(), name='about_us'),

    # JWT Token URLs
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subscriptions/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    SubscriptionsList, SubscriptionView, create_subscription_session,
    create_book_purchase_session, payment_completed, payment_canceled,
    SubscriptionViewSet
)
from . import webhook

router = DefaultRouter()
router.register(r'api/subscriptions', SubscriptionViewSet, basename='subscriptions')

app_name = 'subscriptions'

urlpatterns = [
    # Django views
    path('', SubscriptionsList.as_view(), name='subscriptions_list'),
    path('subscription/<int:pk>/', SubscriptionView.as_view(), name='subscription_detail'),
    path('create-subscription-session/<int:plan_id>/', create_subscription_session, name='create_subscription_session'),
    path('create-book-purchase-session/<int:book_id>/', create_book_purchase_session,
         name='create_book_purchase_session'),
    path('completed/', payment_completed, name='completed'),
    path('canceled/', payment_canceled, name='canceled'),
    path('webhook/', webhook.stripe_webhook, name='stripe_webhook'),

    # DRF views
    path('', include(router.urls)),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Online Book Store</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">


    <link rel="stylesheet" href="{% static 'base.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<header>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'home' %}">Online Book Store</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'books:book_list' %}">Books</a></li>
                <li><a href="{% url 'books:author_list' %}">Authors</a></li>
                <li><a href="{% url 'subs:subscriptions_list' %}">Pricing</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'books:bookmarks' %}">Bookmarks</a></li>
                {% endif %}
                <li><a href="{% url 'about_us' %}">About Us</a></li>
                <div class="search-container">
                    <form action="{% url 'books:search' %}" method="GET">
                        <input type="text" name="query" placeholder="Search for books..." required>
                        <button type="submit">Search</button>
                    </form>
                </div>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}

                <li class="username_logout">
                    <div class="user-info">
                        <a href="{% url 'profile' %}" class="username-link">
                            {% if user.profile.photo %}
                            <img src="{{ user.profile.photo.url }}" alt="Profile Photo"
                                 class="profile-photo img-circle">
                            {{ user.username }}
                            {% else %}
                            <span class="glyphicon glyphicon-user"></span> {{ user.username }}
                            {% endif %}
                        </a>
                        <form method="POST" action="{% url 'logout' %}" id="logoutForm" style="display: inline;">
                            {% csrf_token %}
                            <button type="button" class="logout-btn" id="logoutButton">
                                <span class="glyphicon glyphicon-log-out"></span> Log Out
                            </button>
                        </form>
                    </div>
                </li>
                {% else %}
                <li><a href="{% url 'register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>
<div class="main-wrapper">
    {% block content %}

    {% endblock %}
</div>

{% if request.path != '/books/about-us/' %}
<footer>
    <p>&copy; 2024 Online Book Store. All rights reserved.</p>
    <div class="contact-info">
        <p>Contact us at: <a href="mailto:info@onlinebookstore.com">info@onlinebookstore.com</a></p>
    </div>
</footer>
{% endif %}
<script>
    // Log Out confirmation
    document.getElementById('logoutButton').addEventListener('click', function(event) {
        var confirmation = confirm("Are you sure you want to log out?");
        if (confirmation) {
            document.getElementById('logoutForm').submit();
        } else {
            event.preventDefault();
        }
    });
</script>

</body>
</html>

templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Search Results{% endblock %}

{% block content %}

<link rel="stylesheet" href="{% static 'books/css/search.css' %}">
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"> <!-- Font Awesome -->

<section class="search-results">
    <div class="container">
        <header class="text-center mb-5">
            <h1>Search Results</h1>
        </header>

        <section id="results">

            {% if book_results %}
            <div class="results-section mb-5">
                <h2 class="text-center">Books</h2>
                <div class="row centered">
                    {% for book in book_results %}
                    <div class="col-md-4 col-sm-6">
                        <div class="card text-center">
                            <div class="card-body">
                                <h5 class="card-title">
                                    <a href="{{ books.get_absolute_url }}" class="card-link">{{ book.title}}</a>
                                </h5>
                                <p class="card-text">
                                    <strong>Author:</strong>
                                    <a href="{{ book.author.get_absolute_url }}" class="card-link">{{ book.author }}</a>
                                </p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endif %}


            {% if author_results %}
            <div class="results-section mb-5">
                <h2 class="text-center">Authors</h2>
                <div class="row centered">
                    {% for author in author_results %}
                    <div class="col-md-4 col-sm-6">
                        <div class="card text-center">

                            <div class="card-body">
                                <h5 class="card-title">
                                    <a href="{% url 'books:author_detail' pk=author.pk %}" class="card-link">{{
                                        author.first_name }} {{ author.last_name }}</a>
                                </h5>
                                <p class="card-text">
                                    <strong>Date of Birth:</strong> {{ author.birth_date }}
                                </p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endif %}


            {% if not book_results and not author_results %}
            <div class="no-results text-center">
                <p>No results found for your query.</p>
            </div>
            {% endif %}
        </section>
    </div>
</section>

{% endblock %}